let parcela1 = 15
let parcela2 = 20
let resultado = 0
var parcela3 = 150
var parcela4 = 200
var resultado2 = 0
let meunome = "Eduardo"
var meunome2 = "Eduardo Miranda de Souza"
let parcelajunta = parcela1